export const FINANCE_TERMS = {
  A: ["ATM", "Account", "Allowance", "Apples (as currency demo)", "Amount", "Asset", "Assets"],
  B: ["Bank", "Bill", "Budget", "Bonus", "Borrow", "Buy", "Bonds", "Befin"],
  C: ["Coin", "Cash", "Card", "Candy", "Cost", "Change", "Capital", "Currency"],
  D: ["Dollar", "Dime", "Deposit", "Debit", "Debt", "Dividend"],
  E: ["Earn", "Expense", "Exchange", "Economy", "Equity"],
  F: ["Fee", "Finance", "Funds", "Fortune", "Fiscal"],
  G: ["Gold", "Gift", "Grant", "Gain"],
  H: ["House", "Hire", "Hoard", "Half"],
  I: ["Income", "Interest", "Invest", "Item", "Inflation"],
  J: ["Jar", "Job", "Jewel", "Join"],
  K: ["Karat", "Kindness", "Keep"],
  L: ["Loan", "Lend", "Loss", "License", "Ledger"],
  M: ["Money", "Mint", "Mall", "Market", "Measure", "Mortgage"],
  N: ["Nickel", "Note", "Near", "Need"],
  O: ["Order", "Offer", "Owe", "Owner"],
  P: ["Penny", "Price", "Piggy bank", "Pay", "Profit", "Purchase", "Portfolio"],
  Q: ["Quarter", "Quest (to save)", "Quantity"],
  R: ["Receipt", "Rent", "Rich", "Reward", "Revenue"],
  S: ["Save", "Spend", "Silver", "Sale", "Store", "Salary", "Share", "Stock", "Stocks", "Savings"],
  T: ["Tax", "Tip", "Trade", "Ticket", "Total", "Treasury"],
  U: ["Unit", "Use", "Utility"],
  V: ["Value", "Vault", "Vendor", "Visit (to bank)"],
  W: ["Wallet", "Wealth", "Want", "Work", "Wages"],
  X: ["Xtra", "Xchange"],
  Y: ["Yard sale", "Yield", "Yearly"],
  Z: ["Zero", "Zillion", "Zone"]
};
