export const FINANCE_KEYWORDS = [
    { term: "Asset", hint: "Something of value that an individual or corporation owns." },
    { term: "Bond", hint: "A fixed income instrument that represents a loan made by an investor to a borrower." },
    { term: "Bank", hint: "A financial institution licensed to receive deposits and make loans." },
    { term: "Capital", hint: "Financial assets, such as funds held in deposit accounts or obtained from financing sources." },
    { term: "Credit", hint: "The ability of a customer to obtain goods or services before payment, based on the trust that payment will be made in the future." },
    { term: "Debt", hint: "An amount of money borrowed by one party from another." },
    { term: "Dividend", hint: "A distribution of a portion of a company's earnings to a class of its shareholders." },
    { term: "Equity", hint: "The value of the shares issued by a company." },
    { term: "Economy", hint: "The wealth and resources of a country or region, especially in terms of the production and consumption of goods and services." },
    { term: "Finance", hint: "The management of large amounts of money, especially by governments or large companies." },
    { term: "GDP", hint: "The total value of goods produced and services provided in a country during one year." },
    { term: "Hedge", hint: "An investment to reduce the risk of adverse price movements in an asset." },
    { term: "Inflation", hint: "A general increase in prices and fall in the purchasing value of money." },
    { term: "Interest", hint: "Money paid regularly at a particular rate for the use of money lent." },
    { term: "Joint Venture", hint: "A business arrangement in which two or more parties agree to pool their resources for a specific task." },
    { term: "KPI", hint: "A quantifiable measure used to evaluate the success of an organization in reaching targets." },
    { term: "Ledger", hint: "A book or other collection of financial accounts of a particular type." },
    { term: "Liquidity", hint: "The availability of liquid assets to a market or company." },
    { term: "Market", hint: "A regular gathering of people for the purchase and sale of provisions, livestock, and other goods." },
    { term: "Net Income", hint: "The amount of money that remains after all expenses have been deducted from a company's total revenue." },
    { term: "Option", hint: "A contract which gives the buyer the right, but not the obligation, to buy or sell an underlying asset." },
    { term: "Profit", hint: "A financial gain, especially the difference between the amount earned and the amount spent." },
    { term: "Pension", hint: "A regular payment made during a person's retirement." },
    { term: "Quantitative Easing", hint: "A monetary policy where a central bank purchases at scale government bonds or other financial assets." },
    { term: "Revenue", hint: "Income, especially when of a company or organization and of a substantial nature." },
    { term: "Stock", hint: "The capital raised by a business or corporation through the issue and subscription of shares." },
    { term: "Salary", hint: "A fixed regular payment, typically paid on a monthly or bi-weekly basis." },
    { term: "Tax", hint: "A compulsory contribution to state revenue, levied by the government." },
    { term: "Underwriting", hint: "The process through which an individual or institution takes on financial risk for a fee." },
    { term: "Valuation", hint: "An estimation of something's worth, especially one carried out by a professional appraiser." },
    { term: "Wallet", hint: "A pocket-sized flat folding case for holding money and plastic cards." },
    { term: "XR", hint: "Extended Reality technology often used in modern high-frequency trading visualization." },
    { term: "Yield", hint: "The income return on an investment, such as the interest or dividends received." },
    { term: "Zero-coupon Bond", hint: "A debt security that doesn't pay interest but is instead sold at a deep discount." },
    { term: "Broker", hint: "A person who buys and sells goods or assets for others." },
    { term: "Audit", hint: "An official inspection of an individual's or organization's accounts." }
];
