export const FINANCE_WORDS = [
    { term: 'STOCK', hint: 'Represents ownership in a company.' },
    { term: 'ASSET', hint: 'Something of value that you own.' },
    { term: 'YIELD', hint: 'The income return on an investment.' },
    { term: 'TRADE', hint: 'Buying or selling financial instruments.' },
    { term: 'BONDS', hint: 'Fixed income instrument; a loan to a borrower.' },
    { term: 'LOANS', hint: 'Money borrowed that must be repaid with interest.' },
    { term: 'BANKS', hint: 'Institutions for depositing and borrowing money.' },
    { term: 'DEBTS', hint: 'Money owed to another party.' },
    { term: 'AUDIT', hint: 'Official inspection of financial accounts.' },
    { term: 'PRICE', hint: 'The amount of money expected for an asset.' },
    { term: 'SHARE', hint: 'A unit of ownership in a company.' },
    { term: 'FUNDS', hint: 'Pools of money for a specific purpose.' },
    { term: 'GRANT', hint: 'Non-repayable funds given by an entity.' },
    { term: 'HEDGE', hint: 'Investment to reduce the risk of price movements.' },
    { term: 'INDEX', hint: 'Statistical measure of change in a securities market.' },
    { term: 'MONEY', hint: 'Medium of exchange for goods and services.' },
    { term: 'ORDER', hint: 'Instruction to buy or sell on a trading venue.' },
    { term: 'PENNY', hint: 'Common term for low-priced stocks.' },
    { term: 'QUOTA', hint: 'A limited quantity or allocation of something.' },
    { term: 'RATES', hint: 'The cost of borrowing money.' },
    { term: 'VALUE', hint: 'The worth of a financial instrument.' },
    { term: 'VAULT', hint: 'A secure space for storing valuables.' },
    { term: 'WAIVE', hint: 'To give up a right or claim.' },
    { term: 'COINS', hint: 'Physical form of currency or digital tokens.' },
    { term: 'ENTRY', hint: 'A record in a financial ledger.' },
    { term: 'FIXED', hint: 'Assets or rates that do not change.' },
    { term: 'GROSS', hint: 'Total amount before any deductions.' },
    { term: 'RISKS', hint: 'The possibility of financial loss.' },
    { term: 'SALES', hint: 'Revenue generated from selling goods.' },
    { term: 'TAXES', hint: 'Compulsory contributions to state revenue.' },
    { term: 'UNITS', hint: 'Measurement of an investment fund.' },
    { term: 'TREND', hint: 'The general direction of a market.' },
    { term: 'BULLS', hint: 'Investors who expect prices to rise.' },
    { term: 'BEARS', hint: 'Investors who expect prices to fall.' },
    { term: 'SWAPS', hint: 'Exchange of one financial instrument for another.' },
    { term: 'DEBIT', hint: 'An entry recording a sum owed or paid out.' },
    { term: 'CREDS', hint: 'An entry recording money received.' },
    { term: 'FLOAT', hint: 'Shares available for public trading.' },
    { term: 'DRAFT', hint: 'A written order to pay a sum of money.' },
    { term: 'SPEND', hint: 'To pay out money for goods or services.' },
    { term: 'SAVED', hint: 'Money set aside for future use.' },
    { term: 'EQUIP', hint: 'Assets used to produce goods or services.' },
    { term: 'CARGO', hint: 'Goods transported as part of trade.' },
    { term: 'BASIC', hint: 'Fundamental level before extras or bonuses.' },
    { term: 'BUYER', hint: 'A person who purchases goods or securities.' },
    { term: 'CARRY', hint: 'The cost of holding a financial position.' },
    { term: 'CLAIM', hint: 'A demand for something as a right or owed.' },
    { term: 'CLASS', hint: 'Category of financial assets or shares.' },
    { term: 'CLOSE', hint: 'The end of a trading session.' },
    { term: 'COSTS', hint: 'Expenses incurred in running a business.' },
    { term: 'CURVE', hint: 'Graph showing interest rates across maturities.' },
    { term: 'CYCLE', hint: 'Recurring pattern of economic expansion and contraction.' },
    { term: 'DAILY', hint: 'Occurring or measured every trading day.' },
    { term: 'DEALS', hint: 'Agreements or transactions between parties.' },
    { term: 'DELTA', hint: 'Rate of change of an option price.' },
    { term: 'DEPOT', hint: 'A place where goods or funds are stored.' },
    { term: 'EARLY', hint: 'Repaying a loan before the due date.' },
    { term: 'EQUAL', hint: 'Having the same value on both sides of a ledger.' },
    { term: 'ERROR', hint: 'A mistake in a financial record or transaction.' },
    { term: 'EXCEL', hint: 'To outperform a benchmark or expectation.' },
    { term: 'EXTRA', hint: 'An additional payment or dividend.' },
    { term: 'FETCH', hint: 'The price an asset obtains when sold.' },
    { term: 'FIATS', hint: 'Government-issued currencies not backed by a commodity.' },
    { term: 'FINES', hint: 'Financial penalties for regulatory breaches.' },
    { term: 'FOREX', hint: 'The market for trading currencies.' },
    { term: 'FORMS', hint: 'Official documents required for financial compliance.' },
    { term: 'FORTH', hint: 'Putting capital forward into an investment.' },
    { term: 'FRAUD', hint: 'Wrongful deception for financial gain.' },
    { term: 'GAINS', hint: 'Profits made from an investment.' },
    { term: 'GAUGE', hint: 'A measure of market sentiment or performance.' },
    { term: 'GLUTS', hint: 'Excess supply driving prices down.' },
    { term: 'GOODS', hint: 'Physical products bought and sold in trade.' },
    { term: 'GRAPH', hint: 'Visual display of financial data over time.' },
    { term: 'GROUP', hint: 'A collection of companies under one parent.' },
    { term: 'GROWN', hint: 'An investment that has increased in value.' },
    { term: 'INFER', hint: 'To deduce financial outcomes from available data.' },
    { term: 'INPUT', hint: 'Resources put into a business or model.' },
    { term: 'ISSUE', hint: 'The release of new shares or bonds to the public.' },
    { term: 'ITEMS', hint: 'Individual entries in a financial statement.' },
    { term: 'JOINT', hint: 'Shared ownership or liability between parties.' },
    { term: 'LABOR', hint: 'Human effort as an economic input.' },
    { term: 'LAPSE', hint: 'Expiry of an option or policy without exercise.' },
    { term: 'LARGE', hint: 'Refers to large-cap companies with big market value.' },
    { term: 'LENDS', hint: 'Provides money temporarily in exchange for interest.' },
    { term: 'LIBOR', hint: 'Benchmark rate banks charge each other for loans.' },
    { term: 'LIMIT', hint: 'A set maximum on a price or credit amount.' },
    { term: 'LINED', hint: 'Secured with assets backing an obligation.' },
    { term: 'LISTS', hint: 'A company becomes listed by joining a stock exchange.' },
    { term: 'LOCAL', hint: 'Independent trader operating on an exchange floor.' },
    { term: 'LOCKS', hint: 'Fixing a rate or price for a future date.' },
    { term: 'LOSES', hint: 'To experience a decline in investment value.' },
    { term: 'MACRO', hint: 'Large-scale economic factors affecting markets.' },
    { term: 'MAKER', hint: 'A firm that provides liquidity by quoting prices.' },
    { term: 'MERGE', hint: 'Two companies combining into one entity.' },
    { term: 'MODEL', hint: 'A framework used to price or analyse assets.' },
    { term: 'NAKED', hint: 'An options position without an offsetting holding.' },
    { term: 'NOTES', hint: 'Short-term debt instruments issued by companies.' },
    { term: 'OFFER', hint: 'The price at which a seller will sell an asset.' },
    { term: 'OPENS', hint: 'The start of a trading session.' },
    { term: 'OWNED', hint: 'Assets held by an individual or institution.' },
    { term: 'PANEL', hint: 'A group of institutions setting a benchmark rate.' },
];