export const FINANCE_WORDS = [
    { term: 'STOCK', hint: 'Represents ownership in a company.' },
    { term: 'ASSET', hint: 'Something of value that you own.' },
    { term: 'YIELD', hint: 'The income return on an investment.' },
    { term: 'TRADE', hint: 'Buying or selling financial instruments.' },
    { term: 'BONDS', hint: 'Fixed income instrument; a loan to a borrower.' },
    { term: 'LOANS', hint: 'Money borrowed that must be repaid with interest.' },
    { term: 'BANKS', hint: 'Institutions for depositing and borrowing money.' },
    { term: 'DEBTS', hint: 'Money owed to another party.' },
    { term: 'AUDIT', hint: 'Official inspection of financial accounts.' },
    { term: 'CLEAR', hint: 'The process of settling a trade.' },
    { term: 'PRICE', hint: 'The amount of money expected for an asset.' },
    { term: 'SHARE', hint: 'A unit of ownership in a company.' },
    { term: 'FUNDS', hint: 'Pools of money for a specific purpose.' },
    { term: 'GRANT', hint: 'Non-repayable funds given by an entity.' },
    { term: 'HEDGE', hint: 'Investment to reduce the risk of price movements.' },
    { term: 'INDEX', hint: 'Statistical measure of change in a securities market.' },
    { term: 'LEDGE', hint: 'Short for a book of financial accounts.' },
    { term: 'MONEY', hint: 'Medium of exchange for goods and services.' },
    { term: 'ORDER', hint: 'Instruction to buy or sell on a venue.' },
    { term: 'PENNY', hint: 'Common term for low-priced stocks.' },
    { term: 'QUOTA', hint: 'A limited quantity of something.' },
    { term: 'RATES', hint: 'The cost of borrowing money.' },
    { term: 'VALUE', hint: 'The worth of a financial instrument.' },
    { term: 'VAULT', hint: 'A secure space for storing valuables.' },
    { term: 'WAIVE', hint: 'To give up a right or claim.' },
    { term: 'BROKE', hint: 'Colloquial term for having no money.' },
    { term: 'COINS', hint: 'Physical form of currency or digital tokens.' },
    { term: 'ENTRY', hint: 'A record in a financial ledger.' },
    { term: 'FIXED', hint: 'Assets or rates that do not change.' },
    { term: 'GROSS', hint: 'Total amount before any deductions.' },
    { term: 'INPUT', hint: 'Resources put into a system.' },
    { term: 'LEVER', hint: 'Using borrowed capital for investment.' },
    { term: 'MARKS', hint: 'Adjusting an asset to its current market price.' },
    { term: 'PLOTS', hint: 'Graphic representation of price movements.' },
    { term: 'RISKS', hint: 'The possibility of financial loss.' },
    { term: 'SALES', hint: 'Revenue generated from selling goods.' },
    { term: 'TAXES', hint: 'Compulsory contributions to state revenue.' },
    { term: 'UNITS', hint: 'Measurement of an investment fund.' },
    { term: 'ZONES', hint: 'Areas of price support or resistance.' },
    { term: 'TREND', hint: 'The general direction of a market.' },
    { term: 'BULLS', hint: 'Investors who expect prices to rise.' },
    { term: 'BEARS', hint: 'Investors who expect prices to fall.' },
    { term: 'SWAPS', hint: 'Exchange of one financial instrument for another.' },
    { term: 'DEBIT', hint: 'An entry recording a sum owed.' },
    { term: 'CREDIT', hint: 'The ability to borrow money or buy on trust.' }
];
